baseURL = "https://blog.makotow.net"
title = "makotow's blog"
author = "makotow"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "Blonde"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "UA-31690675-2"

# Disqus Comment System
#disqusShortname = ""
canonifyurls = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "7"
# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "true"

image = "/images/post/default.jpg"

[[params.customCSS]]
    href = "/css/font.css"

#  [[params.customCSS]]
#    href = "/css/syntax.css"

  [[params.customCSS]]
    href = "/css/layout.css"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

#  [[menu.main]]
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact/"
#    weight = 3
#  [[menu.main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories/"
#    weight = 4
#
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags"
#    weight = 5

#  [[menu.main]]
#    identifier = "archives"
#    name = "Archives"
#    url = "/archives"
#    weight = 6

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/makotow"
    weight = 7

  [[menu.main]]
    identifier = "twitter"
    name = "twitter"
    url = "https://twitter.com/makotow"
    weight = 8

  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 9
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
