# Tranquilpeak
# Version : 0.4.7-BETA
# Author : Thibaud Leprêtre

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/images` folder and
# use grunt task `build` to synchronize assets

baseURL = "https://blog.makotow.net/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "makotow's blog"
theme = "hugo-tranquilpeak-theme"
googleAnalytics = "UA-31690675-2"
paginate = 7
canonifyurls = true

# [permalinks]
#   post = "/:year/:month/:slug/"

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Makoto Watanabe"
  bio = "Kubernetes enthusiast<br>CSI Watcher<br>Keyboard enthusiast<br>"
  job = "Solutions Architect"
  location = "Japan"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  #gravatarEmail = "thibaud.lepretre@gmail.com"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "https://lh3.googleusercontent.com/2NYvGUnWkVnzvO9_L62bMQJVwrEZTxLbjSuzVha1UlkxjVFDXpqaldS176w711ypa4GTxl-y5LuJ92Ey4zOqGSRSyBF5DaFOjhG4Ze4PEBiTH4fqeCnJo9gWROXWXhh6bpQltvEhFX1iFRY7jCHblqUvJoNVISdJwbJUzjxrrUYtKe-jd_twRTc9lhxJJIlgMDb1Gvc5eztgquVGidRXJiykuPhyEV459JCiBzUZrfW_wgOGs7SyMsFetOJUmHiopOnMX4VhIUGjl4IPiCBrpQnRSGGK5s7QzbG3pJrX3RELbEgEe132cjebNeOPXBzLDOGfg_1zkKnWCLL0saqMdDQwz6gH7rRs26jgKmvYQfF6ybmU1RgizGMD-MIisKGTTFHTMjSImPFcexRrVgZL1q3wudGTQLVk-SobpfUR83dmJenpgcIwyV5no_nkvUoD48zjXEjLy-24kCHxS_xJ6Wi8Az7HFe5qLbC9j665C-w7FVtifYjbWuMFEigr-HMLEVv0uXYSapArNKbzSI5ds9D9fH9c_W2xhE4AJcZvdwzWgHmOBy_iAfpNb_IKNb8vhzIM9pNjy5Jfr0mzzD5XUkB9kWiyztduUgINm87PYT03hiHvTY5PQfm2wQuSb9YYLGQFhGnup_TbQwYgA6nl0l7ClQxKZQZK4HGyoyd3xT1g63wpfgknbFhYmr43nQlWGdVtJJCz_gizhrCL2tM34akf3Pz9fRumJaE-yrHonFx5eLojbqX5w8Y=s256-no"
  # Your Twitter username without the @. E.g : thibaudlepretre
  twitter = "makotow"
  # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
  # googlePlus = "+ThibaudLepretre"

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/#about"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/makotow"

[[menu.links]]
  weight = 2
  identifier = "twitter"
  name = "twitter"
  pre = "<i class=\"sidebar-button-icon fa fab fa-twitter\"></i>"
  url = "https://twitter.com/makotow"

[[menu.misc]]
  weight = 1
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006
  # dateFormat = "2 January 2006"

  # Global keywords configuration. Following keywords will be add to every pages
  # keywords = ["development", "next-gen"]

  # Syntax highlighter, possible choice between: "highlight.js" (recommanded) and "prism.js" (experimental)
  # You can comment it to disable syntax highlighting
  syntaxHighlighter = "highlight.js"

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading = true

  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo".
  # If false it will flat categories.
  hierarchicalCategories = true

  description = "makotow's blog"

  # Customization
  # Define the behavior of the sidebar
  # 1: Display extra large sidebar on extra large screen, large sidebar on large screen,
  #    medium sidebar on medium screen and header bar on small screen and
  # extra large sidebar is swiped on extra large screen and large sidebar on all lower screen (default)
  # 2: Display large sidebar on large screen, medium sidebar on medium screen and
  #    header bar on small screen and large sidebar is swiped
  # 3: Display medium sidebar on large and medium screen and header bar on small screen and
  #    medium sidebar is swiped
  # 4: Display header bar on all screens, extra large sidebar is swiped on extra large screen and
  #    large sidebar is swiped on all lower screens
  # 5: Display header bar on all screens and large sidebar is swiped on large screen
  # 6: Display header bar on all screens and medium sidebar is swiped
  sidebarBehavior = 2

  # Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
  # There is many free CDN like Cloudinary or you can also use indirectly
  # by using services like Google Photos.
  # Current image is on AWS S3 and delivered by AWS CloudFront.
  # Otherwise put your image, for example `cover.jpg` in folder `static/images/`,
  # and use relative url : `images/cover.jpg`
  # coverImage = "images/cover.jpg"
  coverImage ="https://lh3.googleusercontent.com/T42JIGajka5NiGWmnSwnlzpxj9bKvK3iiN-LhZ71k3yBJDDA8mmlimf69IxHCkUf_q_ehFdVXj0_P7LFhgSnU8Z-Oj_Uj4mcmuz2diy2K8lfCiHH4XgPnqJ_hHIVznsEKPKZgRwd41oX3sAutXLNq7kk0M3tOiQiOYYBVtrZxQ7bi2HOAePnpl-CR-vofXkD_3I5kQCVxb-DjBy7yg_p8L9GJcKBerOno4YKqxjjDMxMTZzENzVRSXUZpIG8qEsKG5LOkqK54hDO5LUZ-tKjhvf9JkLKG_8CaqDHDwAhEkaOzNPkHpmx1RCAwTE1HqlDLOAkN6Een8VLHGE07i_PmJuea2Hl3yz-HhMNrZB6xlY-Cg_6h-EeUAivrB6FVv7fBEBG09dCLWyPC3aTtYap0JeQzyT2902bK62nSUG302Js8xBGiA13sZ6GS525qmAI95Pdz5LwBT_eaHp9IbOjbOaw057Az2c9aMFZvS13Uk6t9BgkZSmzjg7avg5QFmqnXaqs62S7uYtBFWU-jkUuYagd80Y8s9lFdvZzmAR9jEVgQtRAT_Y2PNCei1t5TUdnTGj3trDYHB1GeUyqodrDrNiSILLUPC0PTyqnyGoYL81LjFujKyJR0iVk5eGrlKnW_rMnJVSsFrpzVObFnzQ1yZpKVTH5HQFu6Njpk2Jb7AC9I3C84bDEdXjqVjfYtrPm71HLtjHLMCnZu0GNo484MqSfKzJA35N4UYvlHUQ39OsEeBhn9sDmtdY=w1952-h1301-no"
  # Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
  imageGallery = true

  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true

  # Display thumbnail image at the right of title in index pages (`right`, `left` or `bottom`)
  # Set this value to `right` if you have old posts to keep the old style on them
  # and define `thumbnailImagePosition` on a post to overwrite this setting
  thumbnailImagePosition = "bottom"
  # Automatically select the cover image or the first photo from the gallery of a post if there is no thumbnail image as the thumbnail image
  # Set this value to `true` if you have old posts that use the cover image or the first photo as the thumbnail image
  # and set `autoThumbnailImage` to `false` on a post to overwrite this setting
  autoThumbnailImage = true

  # Your favicon path, default is "/favicon.png"
  # favicon = "/favicon.png"

  # Header configuration
  # The link at the right of the header is customizable
  # You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
  # By default, author's gravatar or author's picture is displayed.
  #     url: /#search
  #     icon: search
  #     class: st-search-show-outputs

  # Display `Next` on left side of the pagination, and `Prev` on right side one.
  # If you set this value to `true`, these positions swap.
  # swapPaginator = true

  # Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
  # they have to be referred from static root. Example
  [[params.customCSS]]
     href = "css/font.css"

  [[params.customCSS]]
     href = "css/syntax.css"

  # Custom JS. Put here your custom JS files. They are loaded after the theme JS;
  # they have to be referred from static root. Example
  # [[params.customJS]]
  #   src = "js/myscript.js"

  # Sharing options
  # Comment and uncomment to enable or disable sharing options
  # If you wanna add a sharing option, read user documentation :
  # Tranquilpeak configuration > Theme configuration > sharing-options
  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook-official"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"

  # Customize link of author avatar in sidebar
  # [params.sidebar.profile]
  #   url = "/#about"

  # Customize copyright value "© 2017 <CUSTOMIZATION>. All Rights Reserved"
  # [params.footer]
  #   copyright = "<a href=\"https://github.com/kakawait\">kakawait</a>"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2